[build]
  command     = "npm run build"
  publish     = "dist"

# Redirige toutes les routes vers index.html
# Indispensable pour une Single Page App React
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
